export const CATEGORY = {
  list: [
    'Airtime/Data',
    'Business',
    'Charity',
    'Clothing & Accessories',
    'Decor',
    'Education',
    'Entertainment',
    'Feeding',
    'Fitness & Wellness',
    'Fuel',
    'Gadgets & Electronics',
    'Gifts',
    'Health & Wellbeing',
    'Insurance',
    'Investment',
    'Kitchen Utensils',
    'Loans/Debts',
    'Misc.',
    'Personal Grooming',
    'Recreation',
    'Religion',
    'Rent',
    'Repair & Maintenance',
    'Salary',
    'Savings',
    'Security',
    'Social Events',
    'Taxes',
    'Toiletries',
    'Transportation',
    'Utility Bills',
    'Vacation',
  ],
};
